/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.main.view;

import com.edu.main.view.pos.Purchase;
import com.edu.main.view.pos.MainReport;
import com.edu.main.view.customer.AddNewCustomer;
import com.edu.main.view.customer.UpdateCustomer;
import com.edu.main.view.customer.CustomerReport;
import com.edu.main.view.customer.DeleteCustomer;
import com.edu.main.view.customer.SearchCustomer;
import com.edu.main.view.product.UpdateProduct;
import com.edu.main.view.product.DeleteProduct;
import com.edu.main.view.product.SearchProduct;
import com.edu.main.view.product.AddNewProduct;
import com.edu.main.view.product.ProductReport;
import com.edu.main.viwe.user.AddNewUser;
import com.edu.main.viwe.user.DeleteUser;
import com.edu.main.viwe.user.UpdateUser;
import com.edu.main.viwe.user.UserList;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Gihan Chathuranga
 */
public class StocKeeprWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public StocKeeprWindow() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayDesktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        productPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        customerPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backPanel = new javax.swing.JPanel();
        productPanels = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        addproductbutton = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        searchproductButton = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        updateproductButton = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        productreportButton = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        deleteproductButton = new javax.swing.JLabel();
        customerPanels = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        addcustomerButton = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        searchcustomerButton = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        updatecustomerButton = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        deletecustomerButton = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        customerreportButton = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        newproductfileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        newcustomerMenuItem = new javax.swing.JMenuItem();
        newuserMenuItem = new javax.swing.JMenuItem();
        purcheMenuItem = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        updateuserMenuItem = new javax.swing.JMenuItem();
        removeuserMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        repoartMenu = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 630));
        setSize(new java.awt.Dimension(765, 475));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1470, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayDesktopPane.setForeground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout displayDesktopPaneLayout = new javax.swing.GroupLayout(displayDesktopPane);
        displayDesktopPane.setLayout(displayDesktopPaneLayout);
        displayDesktopPaneLayout.setHorizontalGroup(
            displayDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        displayDesktopPaneLayout.setVerticalGroup(
            displayDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(displayDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 1050, 480));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Engravers MT", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EsyPOS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 320, 80));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Point of sale System ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 280, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gihan Chathuranga\\Desktop\\NCR-P1230-Display-Terminal.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 190, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 180));

        jPanel3.setBackground(new java.awt.Color(22, 38, 80));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 100));

        productPanel.setBackground(new java.awt.Color(102, 111, 140));
        productPanel.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(102, 111, 140));
        jPanel6.setPreferredSize(new java.awt.Dimension(164, 105));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("                                 Customers");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerPanel.setBackground(new java.awt.Color(102, 111, 140));
        customerPanel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("                                Products");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        customerPanel.add(jLabel6);
        jLabel6.setBounds(0, 10, 310, 27);

        jPanel5.setBackground(new java.awt.Color(102, 111, 140));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(productPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1370, 70));

        jPanel4.setBackground(new java.awt.Color(0, 13, 46));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Log Out");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 80, 480));

        backPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productPanels.setBackground(new java.awt.Color(22, 38, 80));

        jPanel7.setBackground(new java.awt.Color(102, 111, 140));

        addproductbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addproductbutton.setForeground(new java.awt.Color(204, 204, 255));
        addproductbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/addprod.png"))); // NOI18N
        addproductbutton.setText("  Add New Product");
        addproductbutton.setMinimumSize(new java.awt.Dimension(0, 0));
        addproductbutton.setPreferredSize(new java.awt.Dimension(60, 45));
        addproductbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addproductbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addproductbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addproductbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        jPanel23.setBackground(new java.awt.Color(102, 111, 140));

        searchproductButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchproductButton.setForeground(new java.awt.Color(204, 204, 255));
        searchproductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/searpro.png"))); // NOI18N
        searchproductButton.setText("   Search Product");
        searchproductButton.setMinimumSize(new java.awt.Dimension(0, 0));
        searchproductButton.setPreferredSize(new java.awt.Dimension(60, 45));
        searchproductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchproductButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchproductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchproductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );

        jPanel24.setBackground(new java.awt.Color(102, 111, 140));

        updateproductButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateproductButton.setForeground(new java.awt.Color(204, 204, 255));
        updateproductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/uppro.png"))); // NOI18N
        updateproductButton.setText("   Update Product");
        updateproductButton.setMinimumSize(new java.awt.Dimension(0, 0));
        updateproductButton.setPreferredSize(new java.awt.Dimension(60, 45));
        updateproductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateproductButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateproductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateproductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        jPanel25.setBackground(new java.awt.Color(102, 111, 140));

        productreportButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productreportButton.setForeground(new java.awt.Color(204, 204, 255));
        productreportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/prore.png"))); // NOI18N
        productreportButton.setText("   Product Report");
        productreportButton.setMinimumSize(new java.awt.Dimension(0, 0));
        productreportButton.setPreferredSize(new java.awt.Dimension(60, 45));
        productreportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productreportButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productreportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productreportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel26.setBackground(new java.awt.Color(102, 111, 140));

        deleteproductButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteproductButton.setForeground(new java.awt.Color(204, 204, 255));
        deleteproductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/delpro.png"))); // NOI18N
        deleteproductButton.setText("   Delete Product");
        deleteproductButton.setMinimumSize(new java.awt.Dimension(0, 0));
        deleteproductButton.setPreferredSize(new java.awt.Dimension(60, 45));
        deleteproductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteproductButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteproductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteproductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout productPanelsLayout = new javax.swing.GroupLayout(productPanels);
        productPanels.setLayout(productPanelsLayout);
        productPanelsLayout.setHorizontalGroup(
            productPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        productPanelsLayout.setVerticalGroup(
            productPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelsLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backPanel.add(productPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 480));

        customerPanels.setBackground(new java.awt.Color(22, 38, 80));

        jPanel11.setBackground(new java.awt.Color(102, 111, 140));

        addcustomerButton.setBackground(new java.awt.Color(153, 153, 255));
        addcustomerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addcustomerButton.setForeground(new java.awt.Color(153, 153, 255));
        addcustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/00addcus.png"))); // NOI18N
        addcustomerButton.setText("Add New Customer");
        addcustomerButton.setMinimumSize(new java.awt.Dimension(0, 0));
        addcustomerButton.setPreferredSize(new java.awt.Dimension(60, 45));
        addcustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcustomerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addcustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addcustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(102, 111, 140));

        searchcustomerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchcustomerButton.setForeground(new java.awt.Color(153, 153, 255));
        searchcustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/00sercus.png"))); // NOI18N
        searchcustomerButton.setText("  Search Customer");
        searchcustomerButton.setMinimumSize(new java.awt.Dimension(0, 0));
        searchcustomerButton.setPreferredSize(new java.awt.Dimension(60, 45));
        searchcustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchcustomerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchcustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchcustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(102, 111, 140));

        updatecustomerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatecustomerButton.setForeground(new java.awt.Color(153, 153, 255));
        updatecustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/00updcu.png"))); // NOI18N
        updatecustomerButton.setText("  Update Customer");
        updatecustomerButton.setMinimumSize(new java.awt.Dimension(0, 0));
        updatecustomerButton.setPreferredSize(new java.awt.Dimension(60, 45));
        updatecustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatecustomerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updatecustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updatecustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(102, 111, 140));

        deletecustomerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletecustomerButton.setForeground(new java.awt.Color(153, 153, 255));
        deletecustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/00cusdel.png"))); // NOI18N
        deletecustomerButton.setText("  Delete Customer");
        deletecustomerButton.setMinimumSize(new java.awt.Dimension(0, 0));
        deletecustomerButton.setPreferredSize(new java.awt.Dimension(60, 45));
        deletecustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletecustomerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletecustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletecustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel27.setBackground(new java.awt.Color(102, 111, 140));

        customerreportButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerreportButton.setForeground(new java.awt.Color(153, 153, 255));
        customerreportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/images/00crt.png"))); // NOI18N
        customerreportButton.setText("  Customer Report");
        customerreportButton.setMinimumSize(new java.awt.Dimension(0, 0));
        customerreportButton.setPreferredSize(new java.awt.Dimension(60, 45));
        customerreportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerreportButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerreportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerreportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout customerPanelsLayout = new javax.swing.GroupLayout(customerPanels);
        customerPanels.setLayout(customerPanelsLayout);
        customerPanelsLayout.setHorizontalGroup(
            customerPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customerPanelsLayout.setVerticalGroup(
            customerPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelsLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backPanel.add(customerPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 480));

        jPanel1.add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 240, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 730));

        newproductfileMenu.setText("File");
        newproductfileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newproductfileMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New Product");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        newproductfileMenu.add(jMenuItem1);

        newcustomerMenuItem.setText("New Customer");
        newcustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcustomerMenuItemActionPerformed(evt);
            }
        });
        newproductfileMenu.add(newcustomerMenuItem);

        newuserMenuItem.setText("New User");
        newuserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuserMenuItemActionPerformed(evt);
            }
        });
        newproductfileMenu.add(newuserMenuItem);

        purcheMenuItem.setText("Purche Product");
        purcheMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purcheMenuItemActionPerformed(evt);
            }
        });
        newproductfileMenu.add(purcheMenuItem);

        jMenuItem6.setText("Print");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        newproductfileMenu.add(jMenuItem6);

        jMenuBar1.add(newproductfileMenu);

        editMenu.setText("Edit");

        updateuserMenuItem.setText("Update User");
        editMenu.add(updateuserMenuItem);

        removeuserMenuItem.setText("Remove User");
        editMenu.add(removeuserMenuItem);
        editMenu.add(jSeparator1);

        jMenuItem9.setText("Update Product");
        editMenu.add(jMenuItem9);

        jMenuItem10.setText("Remove Product");
        editMenu.add(jMenuItem10);
        editMenu.add(jSeparator2);

        jMenuItem11.setText("Update Customer");
        editMenu.add(jMenuItem11);

        jMenuItem12.setText("Remove Customer");
        editMenu.add(jMenuItem12);

        jMenuBar1.add(editMenu);

        viewMenu.setText("View");

        jMenu6.setText("Search User");

        jMenuItem13.setText("By Name");
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("By ID");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("By Type");
        jMenu6.add(jMenuItem15);

        viewMenu.add(jMenu6);

        jMenu7.setText("Search Product");

        jMenuItem16.setText("By Name");
        jMenu7.add(jMenuItem16);

        jMenuItem17.setText("By ID");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenuItem20.setText("By Type");
        jMenu7.add(jMenuItem20);

        viewMenu.add(jMenu7);

        jMenu8.setText("Search Customer");

        jMenuItem18.setText("By Name");
        jMenu8.add(jMenuItem18);

        jMenuItem19.setText("By ID");
        jMenu8.add(jMenuItem19);

        viewMenu.add(jMenu8);

        jMenuBar1.add(viewMenu);

        repoartMenu.setText("Report");

        jMenuItem21.setText("Product Repoart");
        repoartMenu.add(jMenuItem21);

        jMenuItem22.setText("Customer Repoart");
        repoartMenu.add(jMenuItem22);

        jMenuBar1.add(repoartMenu);

        helpMenu.setText("Help");

        jMenuItem23.setText("Shortcuts");
        helpMenu.add(jMenuItem23);

        jMenuItem24.setText("About Us");
        helpMenu.add(jMenuItem24);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        displayDesktopPane.removeAll();
        AddNewProduct obj = new AddNewProduct();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void addproductbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addproductbuttonMouseClicked
        displayDesktopPane.removeAll();
        AddNewProduct obj = new AddNewProduct();

        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);

        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_addproductbuttonMouseClicked

    private void searchproductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchproductButtonMouseClicked
        displayDesktopPane.removeAll();
        SearchProduct obj = new SearchProduct();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_searchproductButtonMouseClicked

    private void updateproductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateproductButtonMouseClicked
        displayDesktopPane.removeAll();
        UpdateProduct obj = new UpdateProduct();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_updateproductButtonMouseClicked

    public void updateProductedditButton() {
        System.out.println("oooooo");
        displayDesktopPane.removeAll();
        UpdateProduct obj = new UpdateProduct();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }

    private void deleteproductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteproductButtonMouseClicked
        displayDesktopPane.removeAll();
        DeleteProduct obj = new DeleteProduct();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_deleteproductButtonMouseClicked

    private void productreportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productreportButtonMouseClicked
        displayDesktopPane.removeAll();
        ProductReport obj = new ProductReport();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_productreportButtonMouseClicked

    private void newproductfileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newproductfileMenuActionPerformed
        displayDesktopPane.removeAll();
        AddNewCustomer obj = new AddNewCustomer();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_newproductfileMenuActionPerformed

    private void purcheMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purcheMenuItemActionPerformed
        displayDesktopPane.removeAll();
        Purchase obj = new Purchase();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_purcheMenuItemActionPerformed

    private void newcustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcustomerMenuItemActionPerformed
        
    }//GEN-LAST:event_newcustomerMenuItemActionPerformed

    private void newuserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuserMenuItemActionPerformed
        displayDesktopPane.removeAll();
        AddNewUser obj = new AddNewUser();
        
        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
                (desktopSize.height - InternalFrameSize.height) / 2);
        
        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_newuserMenuItemActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        //posPanels.setVisible(false);
        productPanels.setVisible(true);
        //customerPanels.setVisible(false);
        //userPanels.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
//        posPanels.setVisible(false);
        productPanels.setVisible(false);
        customerPanels.setVisible(true);
//        userPanels.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void addcustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcustomerButtonMouseClicked
        displayDesktopPane.removeAll();
        AddNewCustomer obj = new AddNewCustomer();

        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
            (desktopSize.height - InternalFrameSize.height) / 2);

        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_addcustomerButtonMouseClicked

    private void searchcustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchcustomerButtonMouseClicked
        displayDesktopPane.removeAll();
        SearchCustomer obj = new SearchCustomer();

        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
            (desktopSize.height - InternalFrameSize.height) / 2);

        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_searchcustomerButtonMouseClicked

    private void updatecustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatecustomerButtonMouseClicked
        displayDesktopPane.removeAll();
        UpdateCustomer obj = new UpdateCustomer();

        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
            (desktopSize.height - InternalFrameSize.height) / 2);

        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_updatecustomerButtonMouseClicked

    private void deletecustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletecustomerButtonMouseClicked
        displayDesktopPane.removeAll();
        DeleteCustomer obj = new DeleteCustomer();

        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
            (desktopSize.height - InternalFrameSize.height) / 2);

        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_deletecustomerButtonMouseClicked

    private void customerreportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerreportButtonMouseClicked
        // TODO add your handling code here:
        displayDesktopPane.removeAll();
        CustomerReport obj = new CustomerReport();

        Dimension desktopSize = displayDesktopPane.getSize();
        Dimension InternalFrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - InternalFrameSize.width) / 2,
            (desktopSize.height - InternalFrameSize.height) / 2);

        displayDesktopPane.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_customerreportButtonMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StocKeeprWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StocKeeprWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StocKeeprWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StocKeeprWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                MainWindow mainWindow = new MainWindow();
//                mainWindow.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                mainWindow.setVisible(true);
                new StocKeeprWindow().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addcustomerButton;
    private javax.swing.JLabel addproductbutton;
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JPanel customerPanels;
    private javax.swing.JLabel customerreportButton;
    private javax.swing.JLabel deletecustomerButton;
    private javax.swing.JLabel deleteproductButton;
    private javax.swing.JDesktopPane displayDesktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem newcustomerMenuItem;
    private javax.swing.JMenu newproductfileMenu;
    private javax.swing.JMenuItem newuserMenuItem;
    private javax.swing.JPanel productPanel;
    private javax.swing.JPanel productPanels;
    private javax.swing.JLabel productreportButton;
    private javax.swing.JMenuItem purcheMenuItem;
    private javax.swing.JMenuItem removeuserMenuItem;
    private javax.swing.JMenu repoartMenu;
    private javax.swing.JLabel searchcustomerButton;
    private javax.swing.JLabel searchproductButton;
    private javax.swing.JLabel updatecustomerButton;
    private javax.swing.JLabel updateproductButton;
    private javax.swing.JMenuItem updateuserMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables

    
}
